imports:
  - behat.common.yml
default:
  extensions:
    Drupal\MinkExtension:
      goutte: ~
      selenium2:
        wd_host: http://localhost:4444/wd/hub
        capabilities:
          extra_capabilities:
            chromeOptions:
              w3c: false
              args:
                - "--start-maximized"
                - "--headless"
                - "--disable-gpu"
          chrome:
            switches:
              - "--headless"
              - "--disable-gpu"
              - "--window-size=2560,1440"
              - "--no-sandbox"
      javascript_session: selenium2
      browser_name: chrome
      base_url: http://127.0.0.1:8888
      files_path: '/home/travis/build/ASU/webspark-drops-drupal7/profiles/openasu/modules/custom/webspark_test/behat'
    Drupal\DrupalExtension:
      blackbox: ~
      drush:
        root: "/home/travis/build/ASU/webspark-drops-drupal7"
      drupal:
        drupal_root: "/home/travis/build/ASU/webspark-drops-drupal7"
      # Look in the profile modules directory and pull in module subcontexts.
      subcontexts:
        paths:
          - "/home/travis/build/ASU/webspark-drops-drupal7/profiles/openasu/modules/custom/webspark_test"
