imports:
    - behat.common.yml
default:
  extensions:
    Behat\MinkExtension:
      base_url: http://127.0.0.1:8888
      files_path: './profiles/openasu/modules/custom/webspark_test/behat'
    Drupal\DrupalExtension:
      drush:
        root: "/home/travis/build/ASU/webspark-drops-drupal7"
      drupal:
        drupal_root: "/home/travis/build/ASU/webspark-drops-drupal7"

      # Look in the profile modules directory and pull in module subcontexts.
      subcontexts:
        paths:
          - "/home/travis/build/ASU/webspark-drops-drupal7/profiles/openasu/modules/custom/webspark_test"
